# Generated by Django 3.0 on 2019-12-21 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyNoteBookApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyNoteBookApp',
            new_name='MyNoteBookModel',
        ),
    ]
